wandb_version: 1

epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.0003
weight_decay:
  desc: null
  value: 0.005
amsgrad:
  desc: null
  value: false
sliding_window:
  desc: null
  value: 48
n_workers:
  desc: null
  value: 8
model_summary:
  desc: null
  value: false
val:
  desc: null
  value: false
wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685563386.396966
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
